version: "3.9"
services:
  zookeeper1:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: zoo1.zk.local
    ports:
      - 2181:2181
    volumes:
      - zookeeper1_data:/bitnami
    networks:
      - zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zoo1.zk.local:2888:3888,zoo2.zk.local:2888:3888,zoo3.zk.local:2888:3888

  zookeeper2:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: zoo2.zk.local
    ports:
      - 2182:2181
    volumes:
      - zookeeper2_data:/bitnami
    networks:
      - zookeeper
    environment:
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zoo1.zk.local:2888:3888,zoo2.zk.local:2888:3888,zoo3.zk.local:2888:3888

  zookeeper3:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: zoo3.zk.local
    ports:
      - 2183:2181
    volumes:
      - zookeeper3_data:/bitnami
    networks:
      - zookeeper
    environment:
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zoo1.zk.local:2888:3888,zoo2.zk.local:2888:3888,zoo3.zk.local:2888:3888

  zoonavigator:
    image: elkozmon/zoonavigator:1.1.1
    hostname: navigator.zk.local
    ports:
      - 9000:9000
    networks:
      - zookeeper
    environment:
      HTTP_PORT: 9000
      CONNECTION_ZKLOCAL1_NAME: ZooKeeper Server 1
      CONNECTION_ZKLOCAL1_CONN: zoo1.zk.local

      CONNECTION_ZKLOCAL2_NAME: ZooKeeper Server 2
      CONNECTION_ZKLOCAL2_CONN: zoo2.zk.local

      CONNECTION_ZKLOCAL3_NAME: ZooKeeper Server 3
      CONNECTION_ZKLOCAL3_CONN: zoo3.zk.local

      AUTO_CONNECT_CONNECTION_ID: ZKLOCAL1

  server0000:
    hostname: server0000.local
    image: systemserver:latest
    build:
      context: .
      dockerfile: src/docker/Dockerfile

    environment:
      - ShardID=0
      - ServerID=0
      - ZookeeperPort=2181
    networks:
      - zookeeper
    ports:
      - "30000:30000" # gRPC
      - "40000:40000" # Rest

  server0001:
    hostname: server0001.local
    image: systemserver:latest
    environment:
      - ShardID=0
      - ServerID=1
      - ZookeeperPort=2181
    networks:
      - zookeeper
    ports:
      - "30001:30001" # gRPC
      - "40001:40001" # Rest

  server0002:
    hostname: server0002.local
    image: systemserver:latest
    environment:
      - ShardID=0
      - ServerID=2
      - ZookeeperPort=2181
    networks:
      - zookeeper
    ports:
      - "30002:30002" # gRPC
      - "40002:40002" # Rest

  server0100:
    hostname: server0100.local
    image: systemserver:latest
    environment:
      - ShardID=1
      - ServerID=0
      - ZookeeperPort=2181
    networks:
      - zookeeper
    ports:
      - "30100:30100" # gRPC
      - "40100:40100" # Rest

  server0101:
    hostname: server0101.local
    image: systemserver:latest
    environment:
      - ShardID=1
      - ServerID=1
      - ZookeeperPort=2181
    networks:
      - zookeeper
    ports:
      - "30101:30101" # gRPC
      - "40101:40101" # Rest

  server0102:
    hostname: server0102.local
    image: systemserver:latest
    environment:
      - ShardID=1
      - ServerID=2
      - ZookeeperPort=2181
    networks:
      - zookeeper
    ports:
      - "30102:30102" # gRPC
      - "40102:40102" # Rest


networks:
  zookeeper:

volumes:
  zookeeper1_data:
    driver: local
  zookeeper2_data:
    driver: local
  zookeeper3_data:
    driver: local