version: "3.9"
services:
  server00:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - ShardID=0
        - ServerID=0
    ports:
      - "20000:20000" # ZooKeeper
      - "30000:30000" # gRPC
      - "40000:40000" # Rest

#  server01:
#    build:
#      context: .
#      args:
#        - ShardID=0
#        - ServerID=1
#    ports:
#      - "20001:20000" # ZooKeeper
#      - "30001:30000" # gRPC
#      - "40001:40000" # Rest

#  server10:
#    build:
#      context: .
#      args:
#        - ShardID=1
#        - ServerID=0
#    ports:
#      - "20100:20000" # ZooKeeper
#      - "30100:30000" # gRPC
#      - "40100:40000" # Rest

#  server11:
#    build:
#      context: .
#      args:
#        - ShardID=1
#        - ServerID=1
#    ports:
#      - "20101:20000" # ZooKeeper
#      - "30101:30000" # gRPC
#      - "40101:40000" # Rest